# Generated by Django 4.0.6 on 2022-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='对应用户的id')),
                ('level', models.IntegerField(verbose_name='评论级别')),
                ('father_id', models.IntegerField(verbose_name='对应父评论的id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('work_id', models.CharField(max_length=50, verbose_name='评论文章的id')),
                ('content', models.TextField(max_length=1024, verbose_name='评论内容')),
            ],
            options={
                'db_table': 'scholar_comment',
            },
        ),
    ]
