# Generated by Django 4.0.6 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=1024, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='father_id',
            field=models.IntegerField(default=0, verbose_name='对应父评论的id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=0, verbose_name='评论级别'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='对应用户的id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='work_id',
            field=models.CharField(default='', max_length=50, verbose_name='评论文章的id'),
        ),
    ]
