# Generated by Django 4.1.2 on 2022-11-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_comnentofworks_alter_comment_work_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comnentofworks", old_name="work_id", new_name="id",
        ),
    ]
