# Generated by Django 4.1.2 on 2022-11-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_rename_work_id_comnentofworks_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ancestor_id",
            field=models.IntegerField(default=0, verbose_name="对应顶级评论的id"),
        ),
    ]
