# Generated by Django 4.1.2 on 2022-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0005_comment_ancestor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentOfComments",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        verbose_name="回复的评论的id",
                    ),
                ),
                (
                    "comment_id_list",
                    models.TextField(default="", max_length=20000, verbose_name="评论id"),
                ),
            ],
            options={"db_table": "scholar_comment_of_comments",},
        ),
    ]
