# Generated by Django 4.1.2 on 2022-11-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0006_commentofcomments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="评论是否被删除"),
        ),
    ]
