# Generated by Django 4.1.2 on 2022-11-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0007_comment_is_deleted"),
    ]

    operations = [
        migrations.RenameModel(old_name="ComnentOfWorks", new_name="CommentOfWorks",),
    ]
