# Generated by Django 4.1.2 on 2022-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0009_comment_reply_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="work_name",
            field=models.CharField(default="", max_length=1024, verbose_name="评论文章的题目"),
        ),
    ]
