# Generated by Django 4.0.6 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='', max_length=1024, verbose_name='消息的内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(default=0, verbose_name='接受者的用户id'),
        ),
    ]
