# Generated by Django 4.1.2 on 2022-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_alter_message_content_alter_message_receiver_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMessageIdList",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="接受消息用户的id"
                    ),
                ),
                (
                    "message_id_list",
                    models.TextField(default="[]", verbose_name="用户接受的消息的id列表"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="author_id",
            field=models.CharField(
                default="", max_length=1024, verbose_name="用户申请的作者的open_alex的id"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="institution",
            field=models.CharField(
                default="", max_length=200, verbose_name="用户申请的作者所属机构名称"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.IntegerField(default=-1, verbose_name="消息的类型"),
        ),
        migrations.AddField(
            model_name="message",
            name="pdf",
            field=models.CharField(default="", max_length=200, verbose_name="文章pdf"),
        ),
        migrations.AddField(
            model_name="message",
            name="real_name",
            field=models.CharField(
                default="", max_length=1024, verbose_name="用户申请的作者的open_alex的name"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reply",
            field=models.TextField(default="", max_length=1024, verbose_name="回复的内容"),
        ),
        migrations.AddField(
            model_name="message",
            name="send_id",
            field=models.IntegerField(default=0, verbose_name="发送消息用户的id"),
        ),
        migrations.AddField(
            model_name="message",
            name="url",
            field=models.CharField(max_length=200, null=True, verbose_name="论文的访问路由"),
        ),
        migrations.AddField(
            model_name="message",
            name="work_name",
            field=models.CharField(default="", max_length=1024, verbose_name="文章名称"),
        ),
        migrations.AddField(
            model_name="message",
            name="work_open_alex_id",
            field=models.CharField(
                default="", max_length=1024, verbose_name="文章的open_alex的id"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(default="", max_length=1024, verbose_name="被评论的内容"),
        ),
    ]
