# Generated by Django 4.0.6 on 2022-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户的id')),
                ('work_id', models.CharField(max_length=50, verbose_name='对应作品的open_alex_id')),
                ('collection_package_id', models.IntegerField(verbose_name='对应收藏夹的id')),
            ],
            options={
                'db_table': 'scholar_collection',
            },
        ),
        migrations.CreateModel(
            name='CollectionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收藏夹的名字')),
                ('user_id', models.IntegerField(verbose_name='对应用户的id')),
                ('sum', models.IntegerField(verbose_name='收藏夹的收藏数目')),
            ],
            options={
                'db_table': 'scholar_collection_package',
            },
        ),
    ]
