# Generated by Django 4.1.2 on 2022-10-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_alter_collectionpackage_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="collection", name="user_id",),
        migrations.AlterField(
            model_name="collection",
            name="work_id",
            field=models.CharField(max_length=200, verbose_name="对应作品的open_alex_id"),
        ),
    ]
