# Generated by Django 4.1.2 on 2022-11-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_collectionpackage_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionpackage",
            name="name",
            field=models.CharField(
                default="默认收藏夹", max_length=200, verbose_name="收藏夹的名字"
            ),
        ),
    ]
