# Generated by Django 4.0.6 on 2022-10-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('introduction', models.TextField(blank=True, default='Leave something to help others get to know you better!', max_length=2048)),
                ('avatar_url', models.CharField(default='', max_length=128, verbose_name='用户头像路径')),
                ('avatar', models.FileField(default='', upload_to='', verbose_name='用户头像')),
                ('is_professional', models.BooleanField(default=False, verbose_name='是否认证')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
