# Generated by Django 4.0.6 on 2022-10-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='scholar_user',
        ),
    ]
