# Generated by Django 4.0.6 on 2022-10-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, default='Leave something to help others get to know you better!', max_length=2048, verbose_name='自我介绍'),
        ),
    ]
