# Generated by Django 4.1.2 on 2022-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_super",
            field=models.BooleanField(default=False, verbose_name="是否为超管"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="邮箱是否已经验证"),
        ),
    ]
