# Generated by Django 4.1.2 on 2022-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_is_super_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_professional",
            field=models.IntegerField(default=-1, verbose_name="是否认证"),
        ),
    ]
