# Generated by Django 4.0.4 on 2022-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_is_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_alex_id',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='对应的open_alex_id'),
        ),
    ]
