# Generated by Django 4.1.2 on 2022-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_open_alex_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowOfUser",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户的id",
                    ),
                ),
                (
                    "follow_id_list",
                    models.TextField(
                        default="", max_length=20000, verbose_name="被关注人的id列表"
                    ),
                ),
            ],
            options={"db_table": "scholar_follow_of_user",},
        ),
    ]
