# Generated by Django 4.0.4 on 2022-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_count',
            field=models.IntegerField(default=0, verbose_name='作者作品数量'),
        ),
    ]
