# Generated by Django 4.0.4 on 2022-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_work_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_message_count',
            field=models.IntegerField(default=0, verbose_name='未读消息个数'),
        ),
    ]
