# Generated by Django 4.1.2 on 2022-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_unread_message_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionOfUser",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户的id",
                    ),
                ),
                (
                    "collection_id_list",
                    models.TextField(
                        default="", max_length=20000, verbose_name="用户收藏夹的id列表"
                    ),
                ),
            ],
            options={"db_table": "collection_of_user",},
        ),
    ]
