# Generated by Django 4.1.2 on 2022-11-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_collectionofuser"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="collectionofuser", table="scholar_collection_of_user",
        ),
    ]
