# Generated by Django 4.1.2 on 2022-11-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_user_real_name"),
        ("user", "0014_alter_collectionofuser_table"),
    ]

    operations = []
