# Generated by Django 4.1.2 on 2022-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_collectionofuser_collection_id_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followofuser",
            name="follow_id_list",
            field=models.TextField(
                default="[]", max_length=20000, verbose_name="被关注人的id列表"
            ),
        ),
    ]
