# Generated by Django 4.0.6 on 2022-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('content', models.TextField(max_length=1024, verbose_name='申请的内容')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否通过')),
            ],
            options={
                'db_table': 'scholar_form',
            },
        ),
    ]
