# Generated by Django 4.0.6 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='content',
            field=models.TextField(default='', max_length=1024, verbose_name='申请的内容'),
        ),
        migrations.AlterField(
            model_name='form',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
    ]
