# Generated by Django 4.0.4 on 2022-11-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='is_pass',
            field=models.IntegerField(default=0, verbose_name='是否通过'),
        ),
    ]
