# Generated by Django 4.0.4 on 2022-11-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_is_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept_Form_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accept_Form_id_list', models.TextField(default='[]', max_length=1024, verbose_name='已经接受的申请的id的列表')),
            ],
        ),
        migrations.CreateModel(
            name='Handling_Form_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Handling_Form_id_list', models.TextField(default='[]', max_length=1024, verbose_name='未处理的申请的id的列表')),
            ],
        ),
        migrations.CreateModel(
            name='Reject_Form_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reject_Form_id_list', models.TextField(default='[]', max_length=1024, verbose_name='已经拒绝的申请的id的列表')),
            ],
        ),
    ]
