# Generated by Django 4.0.4 on 2022-11-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_delete_accept_form_list_delete_reject_form_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_list',
            fields=[
                ('Form_id_list', models.TextField(default='[]', max_length=1024, verbose_name='未处理的申请的id的列表')),
                ('type', models.IntegerField(primary_key=True, serialize=False, verbose_name='申请处理状态')),
            ],
        ),
        migrations.DeleteModel(
            name='Handling_Form_list',
        ),
    ]
