# Generated by Django 4.0.4 on 2022-11-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_form_list_delete_handling_form_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_list',
            old_name='type',
            new_name='id',
        ),
    ]
