# Generated by Django 4.0.4 on 2022-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_rename_type_form_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
