# Generated by Django 4.0.4 on 2022-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_remove_form_user_id_alter_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
