# Generated by Django 4.0.4 on 2022-11-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_form_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_list',
            new_name='FormList',
        ),
        migrations.RenameField(
            model_name='formlist',
            old_name='Form_id_list',
            new_name='form_id_list',
        ),
    ]
