# Generated by Django 4.0.6 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='open_alex_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='对应的open_alex_id'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='对应的用户id'),
        ),
    ]
