# Generated by Django 4.1.2 on 2022-10-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_alter_author_open_alex_id_alter_author_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="open_alex_id",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=200,
                verbose_name="对应的open_alex_id",
            ),
        ),
    ]
