# Generated by Django 4.0.4 on 2022-11-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_open_alex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='对应的用户id'),
        ),
    ]
