# Generated by Django 4.0.4 on 2022-11-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_is_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_id',
            new_name='id',
        ),
    ]
