# Generated by Django 4.0.4 on 2022-11-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_rename_user_id_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_pass',
        ),
        migrations.AlterField(
            model_name='author',
            name='open_alex_id',
            field=models.CharField(db_index=True, default='', max_length=200, primary_key=True, serialize=False, verbose_name='对应的open_alex_id'),
        ),
    ]
