# Generated by Django 4.0.4 on 2022-11-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_remove_author_id_remove_author_is_pass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='open_alex_id',
            new_name='id',
        ),
    ]
