# Generated by Django 4.0.6 on 2022-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_alex_id', models.CharField(db_index=True, max_length=50, verbose_name='对应的open_alex_id')),
                ('author_id', models.CharField(db_index=True, max_length=50, verbose_name='对应作者的open_alex_id')),
                ('url', models.CharField(max_length=50, verbose_name='论文的访问路由')),
                ('is_delete', models.BooleanField(default=False, verbose_name='论文是否删除')),
            ],
            options={
                'db_table': 'scholar_work',
            },
        ),
    ]
