# Generated by Django 4.0.4 on 2022-11-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='', verbose_name='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='UploadWorkPdfFormList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_list', models.TextField(default='[]', verbose_name='申请上传论文pdf的表单id的列表')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('user_id', models.IntegerField(null=True, verbose_name='上传pdf的用户id')),
                ('id', models.CharField(db_index=True, default='', max_length=200, primary_key=True, serialize=False, verbose_name='对应作品的open_alex_id')),
                ('author_id', models.CharField(db_index=True, default='', max_length=200, verbose_name='上传pdf的作者的open_alex_id')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='论文的访问路由')),
                ('pdf', models.FileField(default='', upload_to='', verbose_name='文章pdf')),
                ('has_pdf', models.IntegerField(default=-1, verbose_name='是否有pdf')),
                ('send_time', models.DateTimeField(verbose_name='上传时间')),
                ('last_user_id', models.IntegerField(null=True, verbose_name='上一个上传pdf的用户id')),
                ('last_author_id', models.CharField(db_index=True, default='', max_length=200, verbose_name='上一个上传pdf的作者的open_alex_id')),
                ('last_url', models.CharField(max_length=200, null=True, verbose_name='上次论文的访问路由')),
                ('last_pdf', models.FileField(null=True, upload_to='', verbose_name='上次文章pdf')),
                ('last_has_pdf', models.IntegerField(default=-1, verbose_name='上次是否有pdf')),
                ('last_send_time', models.DateTimeField(null=True, verbose_name='上次上传时间')),
            ],
            options={
                'db_table': 'scholar_work',
            },
        ),
    ]
