# Generated by Django 4.0.6 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='author_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='对应作者的open_alex_id'),
        ),
        migrations.AlterField(
            model_name='work',
            name='open_alex_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='对应的open_alex_id'),
        ),
    ]
