# Generated by Django 4.0.4 on 2022-11-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pdf', models.FileField(null=True, upload_to='', verbose_name='上次文章pdf')),
            ],
        ),
    ]
