# Generated by Django 4.1.2 on 2022-10-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_alter_work_author_id_alter_work_open_alex_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="author_id",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=200,
                verbose_name="对应作者的open_alex_id",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="open_alex_id",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=200,
                verbose_name="对应的open_alex_id",
            ),
        ),
    ]
