# Generated by Django 4.0.4 on 2022-11-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='last_pdf',
        ),
        migrations.AddField(
            model_name='file',
            name='pdf',
            field=models.FileField(null=True, upload_to='', verbose_name='pdf'),
        ),
    ]
