# Generated by Django 4.0.4 on 2022-11-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_author_id_alter_work_open_alex_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWorkPdfForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='发送申请的用户id')),
                ('author_id', models.CharField(db_index=True, default='', max_length=200, verbose_name='发送申请的用户认领的作者的open_alex_id')),
                ('word_id', models.CharField(db_index=True, default='', max_length=200, verbose_name='申请的论文的open_alex_id')),
                ('send_time', models.TimeField(verbose_name='申请时间')),
                ('url', models.CharField(max_length=200, verbose_name='论文的访问路由')),
                ('flag', models.IntegerField(default=0, verbose_name='处理状态')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.CharField(max_length=200, verbose_name='论文的访问路由'),
        ),
    ]
