# Generated by Django 4.0.4 on 2022-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_file_last_pdf_file_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='open_alex_id',
            new_name='id',
        ),
    ]
