# Generated by Django 4.0.4 on 2022-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_uploadworkpdfform_alter_work_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWorkPdfFormList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_list', models.TextField(default='[]', verbose_name='申请上传论文pdf的表单id的列表')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='has_pdf',
            field=models.IntegerField(default=-1, verbose_name='是否有pdf'),
        ),
        migrations.AlterField(
            model_name='work',
            name='author_id',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='上传pdf的作者的open_alex_id'),
        ),
        migrations.AlterField(
            model_name='work',
            name='open_alex_id',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='对应作品的open_alex_id'),
        ),
    ]
