# Generated by Django 4.0.6 on 2022-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.IntegerField(verbose_name='关注人的id')),
                ('followed_id', models.IntegerField(verbose_name='被关注人的id')),
            ],
            options={
                'db_table': 'scholar_follow',
            },
        ),
    ]
