# Generated by Django 4.0.6 on 2022-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=50, verbose_name='对应作品的open_alex_id')),
                ('user_id', models.IntegerField(verbose_name='对应用户的id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
            ],
            options={
                'db_table': 'scholar_history',
            },
        ),
    ]
