# Generated by Django 4.0.6 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='对应用户的id'),
        ),
        migrations.AlterField(
            model_name='history',
            name='work_id',
            field=models.CharField(default='', max_length=50, verbose_name='对应作品的open_alex_id'),
        ),
    ]
