# Generated by Django 4.1.2 on 2022-11-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_alter_history_user_id_alter_history_work_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="work_id",
            field=models.CharField(
                default="", max_length=200, verbose_name="对应作品的open_alex_id"
            ),
        ),
    ]
