# Generated by Django 4.0.6 on 2022-12-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_work_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='history',
            name='work_id',
        ),
        migrations.AddField(
            model_name='history',
            name='history_list',
            field=models.TextField(default='', verbose_name='用户的搜索历史'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户的id'),
        ),
    ]
