# Generated by Django 4.0.6 on 2022-12-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_history_created_time_remove_history_work_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_id',
        ),
    ]
