# Generated by Django 4.0.6 on 2022-12-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_remove_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='用户的id'),
        ),
    ]
